[build.environment]
  NODE_VERSION = "16.20.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "response"
  [headers.rules]
  patterns = ["/*"]
  headers = [
    { key = "Cache-Control", value = "max-age=31536000, immutable" },
    { key = "Content-Encoding", value = "gzip" }
  ]

[[headers]]
  for = "response"
  [headers.rules]
  patterns = ["/*.js", "/*.css", "/*.jpg", "/*.jpeg", "/*.png", "/*.ico"]
  headers = [
    { key = "Cache-Control", value = "max-age=31536000" }
  ]

[[headers]]
  for = "response"
  [headers.rules]
  patterns = ["/"]
  headers = [
    { key = "Cache-Control", value = "no-cache, no-store, must-revalidate" },
    { key = "Pragma", value = "no-cache" },
    { key = "Expires", value = "0" }
  ]
