[build.environment]
  NODE_VERSION = "16.20.0"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[headers]
[[headers.rules]]
patterns = ["/*.js", "/*.css", "/*.jpg", "/*.jpeg", "/*.png", "/*.ico"]
headers = [
  { key = "Cache-Control", value = "max-age=31536000, immutable" }
]

[[headers]]
for = "/"
[headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"
